AccountingModule::Asset.create!(code: 111_601, name: 'Revolving Fund (Cash Advance)')
AccountingModule::Asset.create!(code: 1_113_021, name: 'Cash in Bank(Common Fund LBP)')
AccountingModule::Asset.create!(code: 1_113_022, name: 'Cash in Bank(MAS Fund LBP)')
AccountingModule::Asset.create!(code: 1_113_023, name: 'Cash in Bank(PNB BIG)')
AccountingModule::Asset.create!(code: 1_113_024, name: 'Cash in Bank(PNB OFW Fund)')
AccountingModule::Asset.create!(code: 1_113_025, name: 'Cash in Bank(RBBI Lamut)')

AccountingModule::Asset.create!(code: 1_113_026, name: 'Other Funds and Deposit (MSCB)')
AccountingModule::Asset.create!(code: 1_113_027, name: 'Other Funds and Deposit (Banco Lagawe - Time Deposit)')
AccountingModule::Asset.create!(code: 1_113_028, name: 'Other Funds and Deposit (Banco Lagawe - Retirement Fund)')
AccountingModule::Asset.create!(code: 1_113_029, name: 'Other Funds and Deposit (Banco Lagawe - Reserve Fund)')
AccountingModule::Asset.create!(code: 11_130_230, name: 'Other Funds and Deposit (Banco Lagawe - CETF Fund)')
AccountingModule::Asset.create!(code: 11_130_231, name: 'Other Funds and Deposit (Banco Lagawe - CDF Fund)')
AccountingModule::Asset.create!(code: 11_130_232, name: 'Other Funds and Deposit (Banco Lagawe - Special Savings)')
AccountingModule::Asset.create!(code: 11_130_233, name: 'Other Funds and Deposit (CLIMBS - Optional Fund)')

AccountingModule::Asset.create!(code: 117_001, name: 'Loans Receivables - Post Dated Check Loan')
AccountingModule::Asset.create!(code: 117_002, name: 'Loans Receivables - Soft Loan')
AccountingModule::Asset.create!(code: 117_003, name: 'Loans Receivables - LBP-Micro Loan')
AccountingModule::Asset.create!(code: 117_004, name: 'Loans Receivables - DOLE Preseed Loan')
AccountingModule::Asset.create!(code: 117_005, name: 'Loans Receivables - DTI NGO MCP2 Loan')

AccountingModule::Asset.create!(code: 117_601,  name: 'Receivable from Gail Dulnuan')
AccountingModule::Asset.create!(code: 117_602,  name: 'Receivable from Bernard Indopia')
AccountingModule::Asset.create!(code: 117_603,  name: 'Receivable from Froylan D. Tuguinay')
AccountingModule::Asset.create!(code: 117_604,  name: 'Receivable from Ronald T. Martin Jr')

AccountingModule::Asset.create!(code: 117_215, name: 'Accounts Receivables - (Kiangan Storefront)')
AccountingModule::Asset.create!(code: 117_216, name: 'Total Trade and Other Receivable')

AccountingModule::Asset.create!(code: 118_101,  name: 'Merchandise Inventory (Kiangan Storefront)')
AccountingModule::Asset.create!(code: 118_102,  name: 'Merchandise Inventory (Eload)')

AccountingModule::Asset.create!(code: 134_004,  name: 'Investment - NORLU CF')
AccountingModule::Asset.create!(code: 134_005,  name: 'Investment - NORLU BF')
AccountingModule::Asset.create!(code: 134_006,  name: 'Investment - IFEDECO')
AccountingModule::Asset.create!(code: 134_007,  name: 'Investment - CLIMBS')
AccountingModule::Asset.create!(code: 134_008,  name: 'Investment - NATTCO')
AccountingModule::Asset.create!(code: 134_009,  name: 'Investment - MSCB')
AccountingModule::Asset.create!(code: 1_340_010,  name: 'Investment - BRANCH')
AccountingModule::Asset.create!(code: 1_340_011,  name: 'Investment - NELCO LEAGUE')

AccountingModule::Asset.create!(code: 141_101,  name: 'Land in Quirino')
AccountingModule::Asset.create!(code: 141_102,  name: 'Land in Nayon')

AccountingModule::Asset.create!(code: 141_301,  name: 'Building - Bodega')
AccountingModule::Asset.create!(code: 141_302,  name: 'Building - Kiangan')
AccountingModule::Asset.create!(code: 141_311,  name: 'Accumulated Depreciation - Buiding Kiangan')
AccountingModule::Asset.create!(code: 141_312,  name: 'Accumulated Depreciation - Buiding Bodega')

AccountingModule::Asset.create!(code: 179_001,  name: 'Miscellaneous Assets - Assets Acquired in Settlement')
AccountingModule::Asset.create!(code: 179_002,  name: 'Water Tank and Cistern')
AccountingModule::Asset.create!(code: 179_103,  name: 'Accumulated Depreciation - Water Tank and Cistern')

AccountingModule::Asset.create!(code: 179_003,  name: 'Communication Facility')
AccountingModule::Asset.create!(code: 179_103,  name: 'Accumulated Depreciation - Communication Facility')

AccountingModule::Asset.create!(code: 173_002,  name: 'Ecoop Software Program')
AccountingModule::Asset.create!(code: 173_010,  name: 'Accumulated Depreciation - Ecoop Software Program')

AccountingModule::Liability.create!(code: 213_003, name: 'Accounts Payable - Alvarez Farm Supply')
AccountingModule::Liability.create!(code: 213_004, name: 'Accounts Payable - Laicom Sales and Promo')
AccountingModule::Liability.create!(code: 213_005, name: 'Accounts Payable - Kaneko Seeds')
AccountingModule::Liability.create!(code: 213_006, name: 'Accounts Payable - FJB-JAB Enterprise')
AccountingModule::Liability.create!(code: 213_007, name: 'Accounts Payable - JMS')
AccountingModule::Liability.create!(code: 213_008, name: 'Accounts Payable - Isabela RC Commercial')
AccountingModule::Liability.create!(code: 213_009, name: 'Accounts Payable - Rebisco')
AccountingModule::Liability.create!(code: 2_130_010, name: 'Accounts Payable - G.V. Cosmetics')
AccountingModule::Liability.create!(code: 2_130_011, name: 'Accounts Payable - D Maya')
AccountingModule::Liability.create!(code: 2_130_012, name: 'Accounts Payable - San Miguel Foods Inc.')
AccountingModule::Liability.create!(code: 2_130_013, name: 'Accounts Payable - Wilmels Store')
AccountingModule::Liability.create!(code: 2_130_014, name: 'Accounts Payable - JL Villarin')
AccountingModule::Liability.create!(code: 2_130_015, name: 'Accounts Payable - AV Luna')

AccountingModule::Liability.create!(code: 215_001, name: 'Loans Payable - P3')
AccountingModule::Liability.create!(code: 215_002, name: 'Loans Payable - CECAP')

AccountingModule::Liability.create!(code: 219_001, name: 'SSS Premium Payable')
AccountingModule::Liability.create!(code: 219_002, name: 'PhilHealth Premium Payable')
AccountingModule::Liability.create!(code: 219_003, name: 'PAG-IBIG Premium Payable')
AccountingModule::Liability.create!(code: 219_004, name: 'PAG-IBI Loan Payable')
AccountingModule::Liability.create!(code: 219_005, name: 'PhilAm Loan Payable')

AccountingModule::Liability.create!(code: 227_001, name: 'Due to NORLU CF')
AccountingModule::Liability.create!(code: 227_002, name: 'Due to MSCB')
AccountingModule::Liability.create!(code: 227_003, name: 'Due to NATTCO')
AccountingModule::Liability.create!(code: 227_004, name: 'Due to IFEDECO')
AccountingModule::Liability.create!(code: 227_005, name: 'Due to NELCO LEAGUE')

AccountingModule::Liability.create!(code: 231_001, name: 'Other Payables - Salaries Treasurer')
AccountingModule::Liability.create!(code: 231_002, name: 'Other Payables - Equipment/Ecoop')
AccountingModule::Liability.create!(code: 231_003, name: 'Other Payables - Bonus Employees')
AccountingModule::Liability.create!(code: 231_004, name: 'Other Payables - Collection Expense')
AccountingModule::Liability.create!(code: 231_005, name: 'Other Payables - COLA Treasurer')
AccountingModule::Liability.create!(code: 231_006, name: 'Other Payables - PGSIP')
AccountingModule::Liability.create!(code: 231_007, name: 'Other Payables - Others')
AccountingModule::Liability.create!(code: 231_008, name: 'Other Payables - Honorariums')
AccountingModule::Liability.create!(code: 231_009, name: 'Other Payables - Office Building Equipment')
AccountingModule::Liability.create!(code: 2_310_010, name: 'Other Payables - Warehouse Improvement')
AccountingModule::Liability.create!(code: 2_310_011, name: 'Other Payables - Generator')
AccountingModule::Liability.create!(code: 2_310_012, name: 'Other Payables - Freezer')

AccountingModule::Liability.create!(code: 248_202, name: 'Mutual Assistance System')
AccountingModule::Liability.create!(code: 248_203, name: 'Retirement Benefit Fund')
AccountingModule::Liability.create!(code: 248_204, name: 'Emergency Trust Fund')
AccountingModule::Liability.create!(code: 248_205, name: 'Cooperative Guaranteed Fund')
AccountingModule::Liability.create!(code: 248_206, name: 'Loan Protection Fund')
AccountingModule::Liability.create!(code: 248_207, name: 'Contingency Fund')
AccountingModule::Liability.create!(code: 248_208, name: 'Municipal Cooperative Training Fund')
AccountingModule::Liability.create!(code: 248_209, name: 'Mutual Assistance System')

AccountingModule::Liability.create!(code: 248_301, name: 'Fund from Main Office')

AccountingModule::Equity.create!(code: 305_001, name: 'Gawad Pitak Award Fund')
AccountingModule::Equity.create!(code: 305_002, name: 'Service Grant from Syngenta')
AccountingModule::Equity.create!(code: 305_003, name: 'Donated Fund for Building')
AccountingModule::Equity.create!(code: 305_004, name: 'Integrated Rural Finance Award')
AccountingModule::Equity.create!(code: 305_005, name: 'Coop NATCCO Fund')

AccountingModule::Equity.create!(code: 306_403, name: 'CETF Local 2')
AccountingModule::Equity.create!(code: 306_404, name: 'Scholarship Program Fund')

AccountingModule::Asset.create(code: 1_171_591, contra: true, name: 'Unearned Interests - Microfinance Loan')

AccountingModule::Revenue.create(code: 4_011_091, name: 'Interest Income from Loans - Microfinance Loan')
AccountingModule::Revenue.create(code: 40_110_921, name: 'Interest Income from Loans - Commercial Loan')
AccountingModule::Revenue.create(code: 40_110_921, name: 'Interest Income from Loans - Pensioner Loan')
AccountingModule::Revenue.create(code: 40_110_922, name: 'Interest Income from Loans - OFW Loan')

AccountingModule::Revenue.create(code: 40_140_191, name: 'Loan Penalties Income - Microfinance Loan')
AccountingModule::Revenue.create(code: 40_140_192, name: 'Loan Penalties Income - Commercial Loan')
AccountingModule::Revenue.create(code: 40_140_193, name: 'Loan Penalties Income - Pensioner Loan')
AccountingModule::Revenue.create(code: 40_140_194, name: 'Loan Penalties Income - Pensioner Loan')
